"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Provider } from "react-redux";
import { store } from "./store";

import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "react-hot-toast";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <Provider store={store}>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <ThemeProvider>
              <Toaster />
              {children}
            </ThemeProvider>
          </body>
        </Provider>
      </SessionProvider>
    </html>
  );
}
